::Replace test file and user name using CTRL+H and replacing all with file you'd like to use

echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd01\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd02\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd04\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd11\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd12\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd13\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd14\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd15\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd16\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd17\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd18\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd19\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd20\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd21\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd22\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd23\c$\Users\jrestivo\Desktop\Phase.bat
echo F| XCOPY C:\Users\jrestivo\Desktop\Phase.bat \\jdcrd24\c$\Users\jrestivo\Desktop\Phase.bat